[base]
Port = ":3000"
Model = "debug"
Env = "staging"
P0Url = "http://localhost:3000"
P1Url = "http://localhost:3000"

[log]
Path = "log/two_party_eddsa.log"
MaxSize = 20
MaxAge = 7
Backups = 10

[db]
Host = "mirrorworld-mysql-db.cxdfzcrpecjt.us-west-2.rds.amazonaws.com"
Port = 3306
UserName = "admin"
Password = "dbpassword"
DBName = "mw_staging"
MaxIdleConns = 10
MaxOpenConns = 30
MaxLifetime = 10